### ISSUE TITLE
使用微信群内AI熊猫Rita对五年级数学下的练习内容进行测试 并更新相应问答对文件 #21

### ISSUE THREAD

**Issue by kaliaoteman** [weijiang2023/algmon-kb#21]
五年级数学下

请更新：

练习21.qa.csv
练习22.qa.csv
练习23.qa.csv
练习24.qa.csv
练习25.qa.csv

五年级数学下课本：
kb/kb/unstructured/domain.math.grade.5.下/core

**Comment by weijiang2023** [comment]
ignore and pass
